[package]
name = "what-the-port"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"

[[bin]]
name = "wtp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive", "cargo"] }
clap-verbosity-flag = "2.1.2"
color-eyre = "0.6.3"
directories = "5.0.1"
ego-tree = "0.6.2"
itertools = "0.13.0"
log = "0.4.21"
once_cell = "1.19.0"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["json"] }
scraper = "0.19.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_with = "3.8.1"
simplelog = "0.12.2"
strum = { version = "0.26.2", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
