[package]
name = "what-the-port"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wtp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive", "cargo"] }
clap-verbosity-flag = "2.1.2"
color-eyre = "0.6.2"
directories = "5.0.1"
ego-tree = "0.6.2"
itertools = "0.12.1"
log = "0.4.20"
once_cell = "1.19.0"
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["json"] }
scraper = "0.18.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_with = "3.6.1"
simplelog = "0.12.1"
strum = { version = "0.26.1", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }
