[package]
name = "what-the-port"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wtp"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4.18", features = ["derive", "cargo"] }
clap-verbosity-flag = "2.1.2"
color-eyre = "0.6.2"
derivative = "2.2.0"
directories = "5.0.1"
itertools = "0.12.1"
log = "0.4.20"
once_cell = "1.19.0"
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["blocking", "json"] }
scraper = "0.18.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_flat_path = "0.1.2"
serde_json = "1.0.113"
simplelog = "0.12.1"
strum = { version = "0.26.1", features = ["derive"] }
tokio = { version = "1.34.0", features = ["full"] }

[build-dependencies]
color-eyre = "0.6.2"
